### ISSUE TITLE
Can't build without R.java?

### ISSUE THREAD

**Issue by dave-gu** [mattfeury/SaucillatorAndroid#5]
Does this repository omit a necessary file? I'd love to get this to build since I've always liked the Saucillator app for Android and I just wanted to follow through with my dream of developing an XY pad synth sequencer based on it which could perhaps do bends and output a midi sequence to be imported into various DAWs and have a VSTi replace the sound generator here.

The line
- import com.mattfeury.saucillator.dev.android.R;
seems to be the only thing preventing it from building, and I would expect that to be referencing a source file R.java … if so would you mind adding it to the repo?

Thanks man and good luck with your startup!
-Dave Gu

**Comment by hdooley** [comment]
Hey it’s been a while since I’ve looked at this, but if memory serves that should be referencing the resource file for the project. I’m not sure there’s supposed to be a corresponding Java file for it. Make sure your resource xml file is in your tree.

Can you post the actual error you’re seeing?

**Comment by dave-gu** [comment]
Wow that was fast!  Yeah I thought it was something like that but I'm totally new to this environment.  What I did was I marked \src as Sources and \res as Resources in Project Structure, but I've searched and I don't see a resource.xml file.  Here's the first few lines of errors, the rest are all the same.
Error:(5, 8) java: The import com.mattfeury.saucillator.dev.android.R cannot be resolved
Error:(32, 22) java: R cannot be resolved to a variable
Error:(36, 47) java: R cannot be resolved to a variable
Error:(37, 47) java: R cannot be resolved to a variable
etc...

**Comment by hdooley** [comment]
So i spent a couple minutes looking into this, and it looks like this project hasn’t aged particularly well. It’s still using the ant build system and doesn’t work out of the box with android studio. Let me spend a bit trying to get it ported over to gradle and get back to you.

**Comment by hdooley** [comment]
Try this PR:
https://github.com/mattfeury/SaucillatorAndroid/pull/6

You should be able to just open the project folder with android studio and build. Let me know if it works for you.

**Comment by hdooley** [comment]
Merged that pr, so pull master if you want to try the gradle version. FYI, R.java should be auto generated somehow from the resources xml file. Not sure how to do it in ANT.

**Comment by mattfeury** [comment]
cool to see some action back here. let me know how it works! code is a little gross as we did all the view management layer ourselves since at this time multiple android views couldn't handle simultaneous touch events, so it's all one view (this is pre-fragments), but the idea behind the synth engine is generally pretty solid.

looks like you guys also got to a similar spot, but also fyi @tompethtel did some work getting this up and running early last year: https://github.com/TomPethtel/SaucillatorAndroid

closing this out. but feel free to re-engage as needed
